- name: "Install facette dependencies"
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - librrd-dev
    - pandoc
    - pkg-config
  tags:
    - facette
    - pkgs

- name: "Download the Go tarball"
  get_url: >
    url={{ go_download_location }}
    dest=/usr/local/src/{{ go_tarball }}
  tags:
    - facette
    - go

- name: "Register the current Go version (if any)"
  shell: |
    /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  tags:
    - facette
    - go

- name: "Extract the Go tarball if Go is not yet installed or if it is not the desired version"
  shell: |
   tar -C /usr/local -xf /usr/local/src/{{ go_tarball }}
  when: go_version|failed or go_version.stdout != go_version_target
  tags:
    - facette
    - go

- name: "Add the Go bin directory to the PATH environment variable for all users"
  copy: >
    src=go-bin.sh
    dest=/etc/profile.d
  tags:
    - facette
    - files
    - go

- name: "Set GOPATH for all users"
  copy: >
    src=go-path.sh
    dest=/etc/profile.d
  tags:
    - facette
    - files
    - go
