- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: debian.yml
  when: ansible_distribution == 'Debian'

- name: "Create the facette user"
  user: >
    name=facette
    state=present
  tags:
    - facette

- name: "Download the facette sources"
  git: >
    repo=https://github.com/facette/facette.git
    dest=/opt/facette
  register: facette_update
  tags:
    - facette

- name: "Make sure the required node version is installed"
  shell: |
    executable=/bin/bash
    creates={{ nvm_dir }}/{{ facette_node_version }}/bin

    source {{ nvm_dir }}/nvm.sh
    nvm install {{ facette_node_version }}
  tags:
    - facette
    - nodejs

- name: "Build facette"
  shell: |
    executable=/bin/bash
    chdir=/opt/facette

    source /etc/profile
    nvm use {{ facette_node_version }}
    make
    [ -f /etc/init.d/facette ] && service facette stop
    make install

  when: facette_update|changed
  notify:
    - Restart Facette
  tags:
    - facette

- name: "Create facette directories"
  file: >
    name={{ item }}
    recurse=yes
    owner=facette
    group=facette
    mode=0755
    state=directory
  with_items:
    - /etc/facette/providers
    - /var/lib/facette
    - /var/run/facette
  tags:
    - facette

- name: "Copy facette configuration file"
  template: >
    src=facette.json
    dest=/etc/facette/facette.json
    mode=0644
    owner=facette
    group=facette
  notify:
    - Restart Facette
  tags:
    - facette
    - files

- name: "Copy facette collectd configuration file"
  template: >
    src=collectd.json
    dest=/etc/facette/providers/collectd.json
    mode=0644
    owner=facette
    group=facette
  notify:
    - Restart Facette
  tags:
    - facette
    - files

- name: "Install Facette init.d script"
  copy: >
    src=facette.init.sh
    dest=/etc/init.d/facette
    owner=root
    group=root
    mode=0700
  notify:
    - Restart Facette
  tags:
    - facette
    - files

- name: "Make sure Facette is running and starts on boot"
  service: >
    name=facette
    state=started
    enabled=yes
    runlevel=5
  tags:
    - facette
