- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: debian.yml
  when: ansible_distribution == 'Debian'

- name: "Create the facette user"
  user: >
    name=facette
    state=present
  tags:
    - facette

- name: "Download the facette sources"
  git: >
    repo=https://github.com/facette/facette.git
    dest=/opt/facette
  register: facette_update
  tags:
    - facette

- name: "Build facette"
  shell: |
    executable=/bin/bash
    chdir=/opt/facette

    source /opt/nvm/nvm.sh
    nvm use {{ node_version }}
    make
    make install

  when: facette_update|changed
  notify:
    - Restart Facette
  tags:
    - facette

- name: "Create facette directories"
  file: >
    name={{ item }}
    recurse=yes
    owner=facette
    group=facette
    mode=0755
    state=directory
  with_items:
    - /etc/facette/providers
    - /var/lib/facette
    - /var/run/facette
  tags:
    - facette

- name: "Copy facette configuration file"
  template: >
    src=facette.json
    dest=/etc/facette/facette.json
    mode=0644
    owner=facette
    group=facette
  notify:
    - Restart Facette
  tags:
    - facette
    - files

- name: "Copy facette collectd configuration file"
  template: >
    src=collectd.json
    dest=/etc/facette/providers/collectd.json
    mode=0644
    owner=facette
    group=facette
  notify:
    - Restart Facette
  tags:
    - facette
    - files

- name: "Install Facette init.d script"
  copy: >
    src=facette.init.sh
    dest=/etc/init.d/facette
    owner=root
    group=root
    mode=0700
  notify:
    - Restart Facette
  tags:
    - facette
    - files

- name: "Make sure Facette is running and starts on boot"
  service: >
    name=facette
    state=started
    enabled=yes
    runlevel=5
  tags:
    - facette

- name: "Add the facette firewall rules file"
  template: >
    src=iptables-facette.j2
    dest=/etc/iptables.d/facette
    mode=0600
    backup=no
    owner=root
    group=root
  tags:
    - facette
    - firewall
    - files

- name: "Apply the facette firewall rules right now"
  shell: |
    /sbin/iptables-restore -v --noflush < /etc/iptables.d/facette
  tags:
    - facette
    - firewall

- name: "Ensure the aeriscloud.d directory exists"
  file: >
    path=/etc/aeriscloud.d
    state=directory
    mode=0755
    owner=root
    group=root
  tags:
    - facette
    - files
    - announce

- name: "Add /etc/aeriscloud.d service definition"
  template: >
    src=aeriscloud-facette.j2
    dest=/etc/aeriscloud.d/facette
    mode=0644
    backup=no
    owner=root
    group=root
  tags:
    - facette
    - files
    - announce
